apiVersion: v1
kind: Service
metadata:
  name: load-balancer-test
  labels:
    app: react-docker-test
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 31001
  selector:
    app: react-docker-test
